### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by lRENyaaa** [klxf/UniqueUUID#1]
由于Floodgate中基岩版玩家名称变化后UUID是不会变化的,所以在基岩版玩家修改名称后可能会被拦截
我没去尝试(懒得搭数据库),所以我这只是提醒一下

**Comment by klxf** [comment]
目前来说玩家更换 ID 后会在数据库中新增一行数据
![LEtHeO.png](https://s1.ax1x.com/2022/04/11/LEtHeO.png)
