### ISSUE TITLE
Support for MariaDB

### ISSUE THREAD

**Issue by AsrielFBI** [klxf/UniqueUUID#3]
[UniqueUUID]: 数据库操作失败，请检查配置文件！
[UniqueUUID]: 数据库操作失败，请检查配置文件！

I have a simple mariadb setted up for this. I just made a new db and user for the plugin and tested its conectivity... ¿Does it need some exact names? I didnt even created a table as it doesnt have an option to specify tables... 

This is my config:
![imagen](https://user-images.githubusercontent.com/56162938/173230916-8fdc2ddb-cdce-44dc-a86b-d00bd200c7cd.png)

**Comment by klxf** [comment]
The data table is automatically created

Hmm... I'm not sure if mariadb is supported...

**Comment by AsrielFBI** [comment]
It doesnt seem so :,/

¿Will it have mariadb compatibility soon thought?

**Comment by AsrielFBI** [comment]
Oh no, it is supported!

Figured out the problem, plugin is allergic to numerical only passwords. As it was a DB without external internet connection I did just made a simple numerical password and it seems the plugin couldnt use it for some security reasons maybe x)

Changed it to a string password with letters and numbers and it now works perfectly fine.
